server {
    listen 80;
    server_name _;
    root /srv/web;
    index index.html;

    client_max_body_size 8m;
    server_tokens off;

    resolver 127.0.0.11 valid=10s ipv6=off;

    location /api/ {
        set $upstream_api vimbo-api:9000;

        include fastcgi_params;
        fastcgi_pass $upstream_api;

        fastcgi_param SCRIPT_FILENAME /srv/app/public/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param DOCUMENT_ROOT /srv/app/public;
        fastcgi_param QUERY_STRING $query_string;
        fastcgi_param REQUEST_URI $request_uri;

        fastcgi_read_timeout 30s;
    }

    location /video/ {
        set $upstream_video http://vimbo-video:3000;
        proxy_pass $upstream_video;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 180s;
        proxy_buffering off;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ /\. {
        deny all;
    }
}
